title : FAFSA API

markdown: kramdown

safe: true
lsi: false
pygments: true
auto: true

source: fafsa-api
destination: fafsa-api

permalink: /:categories/:year/:month/:day/:title 
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

paginate: 1000
paginate_path: "/blog/page:num"

production_url : http://ed-data.github.io/fafsa-api/

BASE_PATH : http://ed-data.github.io/fafsa-api/

archive_path: /archive.html
categories_path : /categories.html
tags_path : /tags.html
